FROM ibm-semeru-runtimes:open-21-jre-jammy

RUN apt-get update && apt-get install -y curl libfreetype6 fontconfig && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the compiled JAR file into the container
COPY target/*.jar app.jar

# Expose the application port
EXPOSE 8080

ENV JAVA_OPTS="-Xmx112m -Xtune:virtualized -XX:+IdleTuningGcOnIdle -Xshareclasses:name=app_scc,cacheDir=/opt/java/scc"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]